sudo: required
services:
  - docker

before_install:
  - docker buid -t sotnical/react-test -f ./client/Dockerfile.dev  ./client

script:
  - docker run -e CI=true sotnical/react-test npm test -- --coverage

after_success:
  - docker build -t sotnical/multi-client ./client
  - docker build -t sotnical/multi-nginx ./nginx
  - docker build -t sotnical/multi-server ./server
  - docker build -t sotnical/multi-worker ./worker

language: generic 